#!/usr/bin/env bash

set -u

INTERVAL=60 # (Seconds) Check interval


# Webhook Jobs Directory (Inside the shared volume)
WEBHOOKS_JOBS_DIR="/data/webhook_jobs"

# The job runs in the host server. The lock file path refers to the host.
LOCK_FILE="/tmp/webhook_deploy.lock"

echo "Watcher started. Lock file: $LOCK_FILE"

while true; do
  # Check if there are any folders in the directory
  HAS_JOBS=$(docker exec data_vol sh -c "ls -A ${WEBHOOKS_JOBS_DIR} | head -n 1")

  if [[ -z "$HAS_JOBS" ]]; then
    # No jobs, sleep and retry based on the INTERVAL
    sleep $INTERVAL
    continue
  fi

  # Jobs found! Let's acquire the lock to ensure atomic execution.
  (
    flock -n 200 || exit 1 # <- HELLO GIL 😂

    curr_date=$(date "+%s")
    echo "[$curr_date] Jobs detected! Locking and starting deploy sequence..."

    # Pega a primeira pasta encontrada
    JOB_FOLDER=$(docker exec data_vol sh -c "find ${WEBHOOKS_JOBS_DIR} -mindepth 1 -maxdepth 1 -type d | head -n 1")

    if [[ -z "$JOB_FOLDER" ]]; then
      echo "[$curr_date] No valid job folder found."
      exit 0
    fi

    echo "[$curr_date] Removing job folder: $JOB_FOLDER"
    docker exec data_vol sh -c "rm -rf ${JOB_FOLDER}"

    # Extrai o nome da pasta
    JOB_NAME=$(basename "$JOB_FOLDER")
    echo "[$curr_date] Processing job: $JOB_NAME"

    DEPLOY_SCRIPT_ROOT="/projects/${JOB_NAME}"
    DEPLOY_SCRIPT="${DEPLOY_SCRIPT_ROOT}/scripts/deploy"
    ENV_FILE="${DEPLOY_SCRIPT_ROOT}/.env"

    [[ -f "${ENV_FILE}" ]] && source "${ENV_FILE}"

    cd "$DEPLOY_SCRIPT_ROOT"

    # Atualiza git apenas se for repositório git E ou ambiente production ou vazio
    if [[ -d .git ]] && [[ -z "$CURRENT_ENV" || "$CURRENT_ENV" == "production" ]]; then
      echo "[$curr_date] Updating git repository (branch: ${DEPLOY_BRANCH:-main})..."
      git fetch origin "${DEPLOY_BRANCH:-main}"
      git reset --hard "origin/${DEPLOY_BRANCH:-main}"
    else
      echo "$DEPLOY_SCRIPT_ROOT nao tem git"
    fi

    if [[ ! -f "$DEPLOY_SCRIPT" ]]; then
      echo "[$curr_date] Deploy script not found: $DEPLOY_SCRIPT. Skipping..."
      docker exec data_vol sh -c "rm -rf ${JOB_FOLDER}"
      exit 0
    fi

    echo "[$curr_date] Running deploy script: $DEPLOY_SCRIPT"

    if /bin/bash "$DEPLOY_SCRIPT"; then
        echo "[$(date "+%s")] Deploy success for $JOB_NAME."
    else
        echo "[$(date "+%s")] Deploy failed for $JOB_NAME."
    fi



  ) 200>"$LOCK_FILE"

  # If flock exited with 1, it means another instance is running.
  if [ $? -eq 1 ]; then
      echo "[$(date "+%s")] Deploy already in progress. Skipping..."
  fi

  sleep $INTERVAL
done


################################################################################

# Instructions
# sudo vim /etc/systemd/system/webhook-watcher.service
#
# [Unit]
# Description=Webhook Watcher for Docker Deployment
# After=network.target

# [Service]
# Type=simple
# WorkingDirectory=/projects/setup-vps/
# ExecStart=/projects/setup-vps/data/scripts/watcher
# Restart=always
# RestartSec=3
# User=mrrobot
# Group=mrrobot

# [Install]
# WantedBy=multi-user.target


################################################################################
# sudo systemctl restart webhook-watcher
# sudo systemctl status webhook-watcher
# # Commands to create
# sudo systemctl daemon-reload
# sudo systemctl enable webhook-watcher
# sudo systemctl start webhook-watcher
# sudo systemctl status webhook-watcher
#
# Commands to remove
# sudo systemctl stop webhook-watcher
# sudo systemctl disable webhook-watcher
# sudo rm /etc/systemd/system/webhook-watcher.service
# sudo systemctl daemon-reload
# # If it insists
# sudo systemctl reset-failed
#
# Check journal live (logs)
# sudo journalctl -u webhook-watcher.service -f
#

################################################################################