#!/usr/bin/env bash

set -Eeuo pipefail

catch_errors() {
  local rc=$?
  printf '\nERROR:\nsrc=%s\nline=%s\nrc=%s\ncmd=%b\n\n' \
    "${BASH_SOURCE[0]}" "$LINENO" "$rc" "$BASH_COMMAND" >&2
  exit "$rc"
}

trap catch_errors ERR

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

/bin/bash -c "'${PROJECT_ROOT}/data/scripts/backup_volumes' before_$(git rev-parse --short HEAD)"

echo docker cp data/. data_vol:/data/.
docker cp data/. data_vol:/data/.
sleep 2

docker compose pull --policy always
docker compose up -d --remove-orphans
docker image prune -f

/bin/bash -c "'${PROJECT_ROOT}/data/scripts/backup_volumes' after_$(git rev-parse --short HEAD)"

echo "OK: deployed $(git rev-parse --short HEAD)"
